### ISSUE TITLE
Host is deleted if down while equipment refresh

### ISSUE THREAD

**Issue by SGobeil** [vincentbernat/wiremaps#5] opened 2011-06-17 02:05 UTC
One of our switches was down while equipment refresh was in progress.  When we tried to enable time machine to go back to the switch config before it went down, it was no longer there.

It would be nice to have a way to confirm switch deletion so the time machine function could still be used.

**Comment by vincentbernat** [comment] 2015-06-15 06:02
Closing, can't reproduce, no news.

**Closed by vincentbernat** 2015-06-15 06:02 UTC
